import numpy as np

result = np.arange(1, 10)
result2 = np.arange(1, 100, 3) 
result3 = np.zeros(10)
result4 = np.ones(10)
result5 = np.linspace(0, 100, 5)
result6 = np.random.randint(60)
result7 = np.random.randint(5, 15)
result8 = np.random.randint(5, 15, 5)
result9 = np.random.rand(6) # It generates 6 numbers between 0 - 1
result10 = np.random.randn(6) # It generates 6 numbers between 0 - 1 but this time negative values included

npArrayOne = np.arange(50)
npMultiDimensionalArrayOne = npArrayOne.reshape(5, 10)
result11 = npMultiDimensionalArrayOne.sum(axis=1)
result12 = npMultiDimensionalArrayOne.sum(axis=0)
result13 = np.random.randint(1, 100, 10)
result14 = result13.max()
result15 = result13.min()
result16 = result13.argmax()
result17 = result13.argmin()
result18 = result13.mean()

print(f"Result..: {result}")
print("==========")
print(f"Result 2..: {result2}")
print("==========")
print(f"Result 3..: {result3}")
print("==========")
print(f"Result 4..: {result4}")
print("==========")
print(f"Result 5..: {result5}")
print("==========")
print(f"Result 6..: {result6}")
print("==========")
print(f"Result 7..: {result7}")
print("==========")
print(f"Result 8..: {result8}")
print("==========")
print(f"Result 9..: {result9}")
print("==========")
print(f"Result 10..: {result10}")
print("==========")
print(f"Result 11..: {result11}")
print("==========")
print(f"Result Numpy Array One..: {npArrayOne}")
print("==========")
print(f"Result Numpy Multidimensional Array One..: \n{npMultiDimensionalArrayOne}")
print("==========")
print(f"Result 12..: {result12}")
print("==========")
print(f"Result 13..: {result13}")
print("==========")
print(f"Result 14..: {result14}")
print("==========")
print(f"Result 15..: {result15}")
print("==========")
print(f"Result 16..: {result16}")
print("==========")
print(f"Result 17..: {result17}")
print("==========")
print(f"Result 18..: {result18}")
print("==========")
